version: '3.8'

services:
  app:
    image: ghcr.io/rpa-for-erp/be_rpa_app:latest
    container_name: be_rpa_app
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - rpa

volumes:
  db_data:

networks:
  rpa:
