version: '3.8'

services:
  app:
    image: ghcr.io/chiencse/be_rpa_app:latest
    container_name: be_rpa_app
    env_file:
      - .env
    ports:
      - 4001:4001
    networks:
      - rpa
    volumes:
      - .env:/app/env/.env

volumes:
  db_data:

networks:
  rpa:
